#!/usr/bin/env python3
"""Generate MacroAnalytics.jsx"""
filepath = r'c:\Users\Alok maurya\OneDrive\Desktop\SIH 127\frontend\src\components\MacroAnalytics.jsx'

L = []
L.append("import React, { useState } from 'react';")
L.append("import { Grid, Activity, ArrowRight, BarChart3, Filter, Zap, AlertTriangle, AlertCircle, CheckCircle2 } from 'lucide-react';")
L.append("")
L.append("const card = { background: 'rgba(15,23,42,0.8)', backdropFilter: 'blur(12px)', padding: '16px', borderRadius: '12px', border: '1px solid #1e293b' };")
L.append("const pill = { display: 'flex', alignItems: 'center', background: '#020617', padding: '4px', borderRadius: '8px', border: '1px solid #1e293b', fontFamily: 'monospace', fontSize: '12px' };")
L.append("const tbtn = (active, clr) => ({ padding: '2px 8px', borderRadius: '4px', background: active ? clr : 'transparent', color: active ? '#fff' : '#94a3b8', border: 'none', cursor: 'pointer', fontWeight: active ? 700 : 400 });")
L.append("const obsColor = kmh => kmh < 20 ? '#f87171' : kmh < 35 ? '#fbbf24' : '#34d399';")
L.append("const ciBar = ci => ci >= 0.7 ? '#ef4444' : ci >= 0.3 ? '#f59e0b' : '#10b981';")
L.append("const sectors = [{ id: 'SEC_01', name: 'Gomti Nagar' }, { id: 'SEC_02', name: 'Hazratganj' }, { id: 'SEC_03', name: 'Charbagh' }, { id: 'SEC_04', name: 'Alambagh' }, { id: 'SEC_05', name: 'Indira Nagar' }];")
L.append("")
L.append("export default function MacroAnalytics({ odFlow, liveCongestion, timeWindows = ['1H', '3H', '12H', '24H'] }) {")
L.append("  const [timeHorizon, setTimeHorizon] = useState('1H');")
L.append("  const [congestionFilter, setCongestionFilter] = useState('ALL');")
L.append("  const [selectedCell, setSelectedCell] = useState(null);")
L.append("  const [hoverCell, setHoverCell] = useState(null);")
print("Part 1 appended")

L.append("  const odMatrixData = odFlow || {")
L.append("    SEC_01: { SEC_01: { count: 420, avgMin: 8, avgKm: 3.2 }, SEC_02: { count: 1250, avgMin: 22, avgKm: 8.4 }, SEC_03: { count: 890, avgMin: 34, avgKm: 12.1 }, SEC_04: { count: 310, avgMin: 41, avgKm: 15.8 }, SEC_05: { count: 670, avgMin: 18, avgKm: 6.5 } },")
L.append("    SEC_02: { SEC_01: { count: 1120, avgMin: 24, avgKm: 8.4 }, SEC_02: { count: 580, avgMin: 6, avgKm: 2.1 }, SEC_03: { count: 1890, avgMin: 16, avgKm: 5.2 }, SEC_04: { count: 740, avgMin: 28, avgKm: 9.6 }, SEC_05: { count: 820, avgMin: 20, avgKm: 7.8 } },")
L.append("    SEC_03: { SEC_01: { count: 780, avgMin: 36, avgKm: 12.1 }, SEC_02: { count: 1640, avgMin: 18, avgKm: 5.2 }, SEC_03: { count: 610, avgMin: 7, avgKm: 2.8 }, SEC_04: { count: 1420, avgMin: 14, avgKm: 4.9 }, SEC_05: { count: 450, avgMin: 38, avgKm: 14.2 } },")
L.append("    SEC_04: { SEC_01: { count: 290, avgMin: 44, avgKm: 15.8 }, SEC_02: { count: 680, avgMin: 30, avgKm: 9.6 }, SEC_03: { count: 1380, avgMin: 15, avgKm: 4.9 }, SEC_04: { count: 490, avgMin: 6, avgKm: 2.4 }, SEC_05: { count: 210, avgMin: 48, avgKm: 17.5 } },")
L.append("    SEC_05: { SEC_01: { count: 610, avgMin: 19, avgKm: 6.5 }, SEC_02: { count: 890, avgMin: 21, avgKm: 7.8 }, SEC_03: { count: 410, avgMin: 39, avgKm: 14.2 }, SEC_04: { count: 190, avgMin: 50, avgKm: 17.5 }, SEC_05: { count: 520, avgMin: 7, avgKm: 2.9 } },")
L.append("  };")
print("Part 2a appended")

L.append("  const segmentData = liveCongestion && liveCongestion.length ? liveCongestion : [")
L.append("    { id: 'SEG_102_105', originCam: 'CAM_102 (Gomti Nagar Main)', destCam: 'CAM_105 (Samta Mulak Chauraha)', distanceMeters: 2400, freeFlowKmh: 60, observedKmh: 14.2, congestionIndex: 0.76, sampleSize: 48, status: 'RED_BOTTLENECK', trend: '+18m delay' },")
L.append("    { id: 'SEG_204_210', originCam: 'CAM_204 (Hazratganj Crossing)', destCam: 'CAM_210 (KD Singh Babu Stadium)', distanceMeters: 1800, freeFlowKmh: 50, observedKmh: 22.5, congestionIndex: 0.55, sampleSize: 82, status: 'AMBER_SLOWDOWN', trend: '+6m delay' },")
L.append("    { id: 'SEG_301_304', originCam: 'CAM_301 (Charbagh Railway Station)', destCam: 'CAM_304 (Naka Hindola)', distanceMeters: 1200, freeFlowKmh: 40, observedKmh: 36.8, congestionIndex: 0.08, sampleSize: 114, status: 'GREEN_FREE_FLOW', trend: 'Normal' },")
L.append("    { id: 'SEG_402_408', originCam: 'CAM_402 (Alambagh Bus Terminal)', destCam: 'CAM_408 (Singar Nagar)', distanceMeters: 3100, freeFlowKmh: 60, observedKmh: 16.5, congestionIndex: 0.73, sampleSize: 63, status: 'RED_BOTTLENECK', trend: '+22m delay' },")
L.append("    { id: 'SEG_501_503', originCam: 'CAM_501 (Indira Nagar Lekhraj)', destCam: 'CAM_503 (Polytechnic Chauraha)', distanceMeters: 2700, freeFlowKmh: 50, observedKmh: 32.0, congestionIndex: 0.36, sampleSize: 95, status: 'AMBER_SLOWDOWN', trend: '+3m delay' },")
L.append("  ];")
L.append("  const redCount = segmentData.filter((s) => s.status === 'RED_BOTTLENECK').length;")
L.append("  const amberCount = segmentData.filter((s) => s.status === 'AMBER_SLOWDOWN').length;")
L.append("  const avgCI = segmentData.length ? segmentData.reduce((a, s) => a + (s.congestionIndex || 0), 0) / segmentData.length : 0;")
L.append("  const totalTrips = Object.values(odMatrixData).reduce((a, row) => a + Object.values(row).reduce((x, c) => x + (c.count || 0), 0), 0);")
L.append("  const filteredSegments = segmentData.filter((s) => {")
L.append("    if (congestionFilter === 'RED') return s.status === 'RED_BOTTLENECK';")
L.append("    if (congestionFilter === 'AMBER') return s.status === 'AMBER_SLOWDOWN';")
L.append("    return true;")
L.append("  });")
L.append("  function getCellHeatStyle(count) {")
L.append("    if (count > 1500) return { background: 'rgba(37,99,235,0.80)', color: '#fff', fontWeight: 700, border: '1px solid rgba(96,165,250,0.5)' };")
L.append("    if (count > 1000) return { background: 'rgba(37,99,235,0.50)', color: '#dbeafe', border: '1px solid rgba(59,130,246,0.30)' };")
L.append("    if (count > 500) return { background: 'rgba(30,58,138,0.40)', color: '#93c5fd', border: '1px solid rgba(30,64,175,0.40)' };")
L.append("    return { background: 'rgba(15,23,42,0.60)', color: '#94a3b8', border: '1px solid #1e293b' };")
L.append("  }")
print("Part 2b appended")

L.append("  return (")
L.append("    <div style={{ width: '100%', backgroundColor: '#020617', padding: '16px', fontFamily: 'sans-serif', color: '#f1f5f9', overflowY: 'auto', borderRadius: '12px', border: '1px solid #1e293b' }}>")
L.append("      <div style={{ ...card, display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: '16px' }}>")
L.append("        <div>")
L.append("          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>")
L.append("            <BarChart3 size={20} color=\"#60a5fa\" />")
L.append("            <h2 style={{ fontSize: '16px', fontWeight: 700, fontFamily: 'monospace', margin: 0, color: '#fff' }}>MACRO TRAFFIC ANALYTICS &amp; OD FLOWS</h2>")
L.append("            <span style={{ fontSize: '10px', fontFamily: 'monospace', padding: '2px 8px', borderRadius: '4px', backgroundColor: 'rgba(59,130,246,0.1)', color: '#60a5fa', border: '1px solid rgba(59,130,246,0.2)' }}>ASYNC CONTINUOUS AGGREGATES</span>")
L.append("          </div>")
L.append("          <p style={{ fontSize: '12px', fontFamily: 'monospace', color: '#94a3b8', margin: '4px 0 0' }}>TimescaleDB Continuous Views + Uber H3 Spatial Density Aggregation</p>")
L.append("        </div>")
L.append("        <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '12px' }}>")
L.append("          <div style={pill}>")
L.append("            {timeWindows.map((h) => (")
L.append("              <button key={h} onClick={() => setTimeHorizon(h)} style={tbtn(timeHorizon === h, '#2563eb')}>{h}</button>")
L.append("            ))}")
L.append("          </div>")
L.append("          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', fontFamily: 'monospace', fontSize: '12px', backgroundColor: '#020617', padding: '6px 12px', borderRadius: '8px', border: '1px solid #1e293b' }}>")
L.append("            <div><span style={{ fontSize: '10px', color: '#64748b', display: 'block' }}>TOTAL TRIPS</span><span style={{ fontWeight: 700 }}>{totalTrips.toLocaleString()}</span></div>")
L.append("            <div style={{ width: '1px', height: '20px', backgroundColor: '#1e293b' }} />")
L.append("            <div><span style={{ fontSize: '10px', color: '#64748b', display: 'block' }}>AVG CI INDEX</span><span style={{ fontWeight: 700, color: '#fbbf24' }}>{avgCI.toFixed(2)}</span></div>")
L.append("            <div style={{ width: '1px', height: '20px', backgroundColor: '#1e293b' }} />")
L.append("            <div><span style={{ fontSize: '10px', color: '#64748b', display: 'block' }}>BOTTLENECKS</span><span style={{ fontWeight: 700, color: '#f87171' }}>{redCount} RED</span></div>")
L.append("          </div>")
L.append("        </div>")
L.append("      </div>")
L.append("      <div style={card}>")
L.append("        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap', gap: '8px' }}>")
print("Part 3a appended")

L.append("          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>")
L.append("            <Grid size={16} color=\"#60a5fa\" />")
L.append("            <h3 style={{ fontSize: '12px', fontFamily: 'monospace', fontWeight: 700, margin: 0 }}>INTER-SECTOR OD FLOW MATRIX ({timeHorizon} WINDOW)</h3>")
L.append("          </div>")
L.append("          <span style={{ fontSize: '11px', fontFamily: 'monospace', color: '#94a3b8' }}>Values = Vehicle Count (hover for stats, click to pin)</span>")
L.append("        </div>")
L.append("        <div style={{ overflowX: 'auto' }}>")
L.append("          <table style={{ width: '100%', textAlign: 'center', borderCollapse: 'collapse', fontFamily: 'monospace', fontSize: '12px' }}>")
L.append("            <thead>")
L.append("              <tr>")
L.append("                <th style={{ padding: '8px', border: '1px solid #1e293b', backgroundColor: '#020617', color: '#64748b', textAlign: 'left', minWidth: '140px', fontWeight: 400 }}>ORIGIN \\ DEST</th>")
L.append("                {sectors.map((s) => (")
L.append("                  <th key={s.id} style={{ padding: '8px', border: '1px solid #1e293b', backgroundColor: '#020617', color: '#60a5fa', minWidth: '110px' }}>{s.name}</th>")
L.append("                ))}")
L.append("              </tr>")
L.append("            </thead>")
L.append("            <tbody>")
L.append("              {sectors.map((orig) => (")
L.append("                <tr key={orig.id}>")
L.append("                  <td style={{ padding: '8px', border: '1px solid #1e293b', backgroundColor: '#020617', textAlign: 'left', fontWeight: 700, color: '#60a5fa' }}>{orig.name}</td>")
L.append("                  {sectors.map((dest) => {")
L.append("                    const cell = (odMatrixData[orig.id] && odMatrixData[orig.id][dest.id]) || { count: 0, avgMin: 0, avgKm: 0 };")
L.append("                    const isSelf = orig.id === dest.id;")
L.append("                    const heat = isSelf ? { background: 'rgba(2,6,23,0.4)', color: '#475569', border: '1px solid #1e293b' } : getCellHeatStyle(cell.count);")
L.append("                    const hov = hoverCell === orig.id + '-' + dest.id;")
L.append("                    return (")
L.append("                      <td key={dest.id} onClick={() => setSelectedCell({ origin: orig.name, dest: dest.name, count: cell.count, avgMin: cell.avgMin, avgKm: cell.avgKm })} onMouseEnter={() => setHoverCell(orig.id + '-' + dest.id)} onMouseLeave={() => setHoverCell(null)} style={{ padding: '12px', cursor: 'pointer', position: 'relative', ...heat }}>")
L.append("                        <div style={{ fontSize: '14px', fontWeight: 700 }}>{cell.count}</div>")
L.append("                        <div style={{ fontSize: '10px', opacity: 0.75 }}>{cell.avgMin}m | {cell.avgKm}km</div>")
L.append("                        {hov && !isSelf && (")
L.append("                          <div style={{ position: 'absolute', bottom: '100%', left: '50%', transform: 'translateX(-50%)', marginBottom: '8px', display: 'flex', flexDirection: 'column', backgroundColor: '#0f172a', border: '1px solid #334155', padding: '8px', borderRadius: '6px', zIndex: 30, fontSize: '10px', whiteSpace: 'nowrap', textAlign: 'left', color: '#e2e8f0' }}>")
L.append("                            <span style={{ fontWeight: 700, color: '#60a5fa' }}>{orig.name} =&gt; {dest.name}</span>")
L.append("                            <span>Volume: {cell.count} vehicles</span>")
L.append("                            <span>Avg Transit: {cell.avgMin} mins</span>")
L.append("                            <span>Avg Distance: {cell.avgKm} km</span>")
L.append("                          </div>")
L.append("                        )}")
L.append("                      </td>")
L.append("                    );")
L.append("                  })}")
L.append("                </tr>")
L.append("              ))}")
L.append("            </tbody>")
L.append("          </table>")
L.append("        </div>")
print("Part 3b (OD matrix) appended")

L.append("        {selectedCell && (")
L.append("          <div style={{ padding: '12px', backgroundColor: '#020617', borderRadius: '8px', border: '1px solid #1e293b', display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontFamily: 'monospace', fontSize: '12px', marginTop: '12px', flexWrap: 'wrap', gap: '8px' }}>")
L.append("            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>")
L.append("              <Zap size={16} color=\"#fbbf24\" />")
L.append("              <span>Selected Corridor: <strong style={{ color: '#60a5fa' }}>{selectedCell.origin} =&gt; {selectedCell.dest}</strong></span>")
L.append("              <span style={{ color: '#475569' }}>|</span>")
L.append("              <span>Volume: <strong style={{ color: '#fff' }}>{selectedCell.count} trips</strong></span>")
L.append("              <span style={{ color: '#475569' }}>|</span>")
L.append("              <span>Avg Speed: <strong style={{ color: '#34d399' }}>{selectedCell.avgMin ? (selectedCell.avgKm / (selectedCell.avgMin / 60)).toFixed(1) : '--'} km/h</strong></span>")
L.append("            </div>")
L.append("            <button onClick={() => setSelectedCell(null)} style={{ background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: '10px', textDecoration: 'underline' }}>CLEAR</button>")
L.append("          </div>")
L.append("        )}")
L.append("      </div>")
L.append("      <div style={{ ...card, marginBottom: 0 }}>")
L.append("        <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>")
L.append("          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>")
L.append("            <Activity size={16} color=\"#34d399\" />")
L.append("            <h3 style={{ fontSize: '12px', fontFamily: 'monospace', fontWeight: 700, margin: 0 }}>SEGMENT SPEED RATIO &amp; BOTTLENECK ENGINE (CI &gt;= 0.70 ALERT)</h3>")
L.append("          </div>")
L.append("          <div style={{ ...pill, alignItems: 'center', gap: '4px' }}>")
L.append("            <Filter size={14} color=\"#64748b\" style={{ marginLeft: '4px' }} />")
L.append("            <button onClick={() => setCongestionFilter('ALL')} style={tbtn(congestionFilter === 'ALL', '#2563eb')}>ALL ({segmentData.length})</button>")
L.append("            <button onClick={() => setCongestionFilter('RED')} style={tbtn(congestionFilter === 'RED', '#dc2626')}>RED ({redCount})</button>")
L.append("            <button onClick={() => setCongestionFilter('AMBER')} style={tbtn(congestionFilter === 'AMBER', '#d97706')}>AMBER ({amberCount})</button>")
L.append("          </div>")
L.append("        </div>")
L.append("        <div style={{ overflowX: 'auto' }}>")
L.append("          <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse', fontFamily: 'monospace', fontSize: '12px' }}>")
print("Part 4a appended")

L.append("            <thead>")
L.append("              <tr style={{ borderBottom: '1px solid #1e293b', backgroundColor: '#020617', color: '#94a3b8' }}>")
L.append("                <th style={{ padding: '12px' }}>CAMERA SEGMENT PAIR</th>")
L.append("                <th style={{ padding: '12px' }}>DISTANCE</th>")
L.append("                <th style={{ padding: '12px' }}>FREE FLOW</th>")
L.append("                <th style={{ padding: '12px' }}>OBSERVED</th>")
L.append("                <th style={{ padding: '12px' }}>CI</th>")
L.append("                <th style={{ padding: '12px' }}>SAMPLE</th>")
L.append("                <th style={{ padding: '12px' }}>STATUS</th>")
L.append("              </tr>")
L.append("            </thead>")
L.append("            <tbody>")
L.append("              {filteredSegments.map((seg) => (")
L.append("                <tr key={seg.id} style={{ borderBottom: '1px solid rgba(30,41,59,0.6)' }}>")
L.append("                  <td style={{ padding: '12px' }}>")
L.append("                    <div style={{ fontWeight: 700, display: 'flex', alignItems: 'center', gap: '6px', color: '#f1f5f9' }}>{seg.originCam} <ArrowRight size={14} color=\"#64748b\" /> {seg.destCam}</div>")
L.append("                    <span style={{ fontSize: '10px', color: '#64748b' }}>{seg.id} · {seg.trend}</span>")
L.append("                  </td>")
L.append("                  <td style={{ padding: '12px', color: '#cbd5e1' }}>{(seg.distanceMeters / 1000).toFixed(1)} km</td>")
L.append("                  <td style={{ padding: '12px', color: '#94a3b8' }}>{seg.freeFlowKmh} km/h</td>")
L.append("                  <td style={{ padding: '12px', fontWeight: 700, color: obsColor(seg.observedKmh) }}>{seg.observedKmh} km/h</td>")
L.append("                  <td style={{ padding: '12px' }}>")
L.append("                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>")
L.append("                      <div style={{ width: '96px', backgroundColor: '#1e293b', height: '8px', borderRadius: '4px', overflow: 'hidden' }}>")
L.append("                        <div style={{ height: '100%', backgroundColor: ciBar(seg.congestionIndex), width: Math.round(seg.congestionIndex * 100) + '%' }} />")
L.append("                      </div>")
L.append("                      <span style={{ fontWeight: 700, color: '#e2e8f0' }}>{seg.congestionIndex.toFixed(2)}</span>")
L.append("                    </div>")
L.append("                  </td>")
L.append("                  <td style={{ padding: '12px', color: '#94a3b8' }}>{seg.sampleSize} veh</td>")
L.append("                  <td style={{ padding: '12px' }}>")
L.append("                    {seg.status === 'RED_BOTTLENECK' ? (")
L.append("                      <span style={{ padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 700, backgroundColor: 'rgba(239,68,68,0.2)', color: '#f87171', border: '1px solid rgba(239,68,68,0.4)', display: 'inline-flex', alignItems: 'center', gap: '4px' }}><AlertTriangle size={12} /> RED BOTTLENECK</span>")
L.append("                    ) : seg.status === 'AMBER_SLOWDOWN' ? (")
L.append("                      <span style={{ padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 700, backgroundColor: 'rgba(245,158,11,0.2)', color: '#fbbf24', border: '1px solid rgba(245,158,11,0.4)', display: 'inline-flex', alignItems: 'center', gap: '4px' }}><AlertCircle size={12} /> SLOWDOWN</span>")
L.append("                    ) : (")
L.append("                      <span style={{ padding: '4px 10px', borderRadius: '4px', fontSize: '10px', fontWeight: 700, backgroundColor: 'rgba(16,185,129,0.2)', color: '#34d399', border: '1px solid rgba(16,185,129,0.4)', display: 'inline-flex', alignItems: 'center', gap: '4px' }}><CheckCircle2 size={12} /> FREE FLOW</span>")
L.append("                    )}")
L.append("                  </td>")
L.append("                </tr>")
L.append("              ))}")
L.append("            </tbody>")
L.append("          </table>")
L.append("        </div>")
L.append("      </div>")
L.append("    </div>")
L.append("  );")
L.append("}")
L.append("")
print("Part 4b (table) appended")

content = '\n'.join(L)
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

# Verify balanced tags
c = content
div_o = c.count('<div')
div_c = c.count('</div>')
tr_o = c.count('<tr')
tr_c = c.count('</tr>')
td_o = c.count('<td')
td_c = c.count('</td>')
tb_o = c.count('<table')
tb_c = c.count('</table>')
ty_o = c.count('<tbody')
ty_c = c.count('</tbody>')
print(f'div: {div_o}/{div_c}, tr: {tr_o}/{tr_c}, td: {td_o}/{td_c}, table: {tb_o}/{tb_c}, tbody: {ty_o}/{ty_c}')
print(f'braces: {c.count(chr(123))}/{c.count(chr(125))}, parens: {c.count(chr(40))}/{c.count(chr(41))}')
print(f'Lines: {c.count(chr(10))+1}')
print('File written successfully')
